// default package
// Generated 05-sep-2013 13:39:34 by Hibernate Tools 3.4.0.CR1

package com.unibert.valenciaevents.app.clases;


import java.util.Date;

/**
 * Usuarios generated by hbm2java
 */

public class Usuario implements java.io.Serializable {


	private Long id;
	
	private String nombre;
	private Long edad;

	private Date ultimaConexion;
	private Long numeroConexion;

	private Date alta;

//	private Set<Comentario> comentarioses = new HashSet<Comentario>(0);

	public Usuario() {
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Long getEdad() {
		return edad;
	}

	public void setEdad(Long edad) {
		this.edad = edad;
	}

	public Date getUltimaConexion() {
		return ultimaConexion;
	}

	public void setUltimaConexion(Date ultimaConexion) {
		this.ultimaConexion = ultimaConexion;
	}

	public Long getNumeroConexion() {
		return numeroConexion;
	}

	public void setNumeroConexion(Long numeroConexion) {
		this.numeroConexion = numeroConexion;
	}

	public Date getAlta() {
		return alta;
	}

	public void setAlta(Date alta) {
		this.alta = alta;
	}

//	public Set<Comentario> getComentarioses() {
//		return comentarioses;
//	}
//
//	public void setComentarioses(Set<Comentario> comentarioses) {
//		this.comentarioses = comentarioses;
//	}


}
